# Generated by Django 5.0 on 2025-11-02 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_tracking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(help_text='Order in the route (same as from_stop order)')),
                ('distance_meters', models.FloatField(help_text='Actual road distance in meters')),
                ('typical_duration_seconds', models.IntegerField(blank=True, help_text='Typical travel time in seconds', null=True)),
                ('polyline_points', models.JSONField(blank=True, default=list, help_text='Array of [lat, lon] points along the road')),
                ('bus_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='bus_tracking.busline')),
                ('from_stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments_from', to='bus_tracking.busstop')),
                ('to_stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments_to', to='bus_tracking.busstop')),
            ],
            options={
                'ordering': ['bus_line', 'order'],
                'indexes': [models.Index(fields=['bus_line', 'order'], name='bus_trackin_bus_lin_921302_idx')],
                'unique_together': {('bus_line', 'from_stop', 'to_stop')},
            },
        ),
    ]
