# bus_tracking/models.py

from django.db import models

class Location(models.Model):
    """
    Represents geographic coordinates (latitude and longitude).
    """
    latitude = models.FloatField()
    longitude = models.FloatField()

    def __str__(self):
        return f"({self.latitude}, {self.longitude})"

class BusLine(models.Model):
    """
    Represents bus routes.
    """
    # FIX: Removed the duplicate bus_line_id. A model can only have one primary key.
    route_id = models.AutoField(primary_key=True)
    route_name = models.CharField(max_length=255)
    route_description = models.TextField(blank=True)
    estimated_travel_time = models.DurationField(null=True, blank=True)
    
    def __str__(self):
        return self.route_name

class BusStop(models.Model):
    """
    Represents bus stops.
    """
    stop_id = models.AutoField(primary_key=True)
    stop_name = models.CharField(max_length=255)
    location = models.ForeignKey(Location, on_delete=models.CASCADE)

    def __str__(self):
        return self.stop_name
    
class BusLineStop(models.Model):
    """
    Intermediate model to link bus lines to stops with a specific order.
    """
    bus_line = models.ForeignKey(BusLine, on_delete=models.CASCADE)
    bus_stop = models.ForeignKey(BusStop, on_delete=models.CASCADE)
    order = models.PositiveIntegerField()

    class Meta:
        ordering = ['order']
        unique_together = ('bus_line', 'bus_stop', 'order')

    def __str__(self):
        return f"{self.bus_line.route_name} - {self.bus_stop.stop_name} ({self.order})"

class RouteSegment(models.Model):
    """
    Represents a segment of a route between two consecutive stops.
    Stores pre-calculated distances and polyline data for accurate tracking.
    """
    bus_line = models.ForeignKey(BusLine, on_delete=models.CASCADE, related_name='segments')
    from_stop = models.ForeignKey(BusStop, on_delete=models.CASCADE, related_name='segments_from')
    to_stop = models.ForeignKey(BusStop, on_delete=models.CASCADE, related_name='segments_to')
    order = models.PositiveIntegerField(help_text="Order in the route (same as from_stop order)")
    
    # Distance and timing information
    distance_meters = models.FloatField(help_text="Actual road distance in meters")
    typical_duration_seconds = models.IntegerField(help_text="Typical travel time in seconds", null=True, blank=True)
    
    # Polyline data (stores intermediate points along the road)
    # Format: JSON array of [lat, lon] pairs
    polyline_points = models.JSONField(default=list, blank=True, help_text="Array of [lat, lon] points along the road")

    class Meta:
        ordering = ['bus_line', 'order']
        unique_together = ('bus_line', 'from_stop', 'to_stop')
        indexes = [
            models.Index(fields=['bus_line', 'order']),
        ]

    def __str__(self):
        return f"{self.bus_line.route_name}: {self.from_stop.stop_name} → {self.to_stop.stop_name}"
    
    def get_distance_km(self):
        """Return distance in kilometers"""
        return self.distance_meters / 1000.0

class Bus(models.Model):
    """
    Represents individual buses in the system.
    """
    bus_id = models.AutoField(primary_key=True)
    license_plate = models.CharField(max_length=50, unique=True)
    qr_code_value = models.CharField(max_length=255, unique=True, blank=True, null=True)
    bus_line = models.ForeignKey(BusLine, on_delete=models.SET_NULL, null=True, blank=True)
    
    # Field to store the last known location for quick access
    current_location = models.ForeignKey(Location, on_delete=models.SET_NULL, null=True, blank=True, related_name='bus_current_location')

    def __str__(self):
        return f"Bus {self.license_plate}"

class BusLocationLog(models.Model):
    """
    Represents a historical log of bus locations.
    """
    bus = models.ForeignKey(Bus, on_delete=models.CASCADE)
    location = models.ForeignKey(Location, on_delete=models.CASCADE)
    timestamp = models.DateTimeField(auto_now_add=True)
    speed = models.FloatField(null=True, blank=True)

    def __str__(self):
        return f"Log for Bus {self.bus} at {self.timestamp}"

class Alert(models.Model):
    """
    Represents alerts generated by the system.
    """
    ALERT_TYPES = (
        ('DELAY', 'Delay'),
        ('OFF_ROUTE', 'Off Route'),
        ('TECHNICAL', 'Technical Issue'),
        ('OTHER', 'Other'),
    )
    alert_id = models.AutoField(primary_key=True)
    bus = models.ForeignKey(Bus, on_delete=models.SET_NULL, null=True, blank=True)
    alert_type = models.CharField(max_length=20, choices=ALERT_TYPES, default='OTHER')
    message = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)
    is_resolved = models.BooleanField(default=False)

    def __str__(self):
        return f"Alert for Bus {self.bus}: {self.message}"